apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-release-values
  namespace: kube-system
data:
  values.yaml: |
    metrics-server:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 200Mi
      nodeSelector:
        nodegroup: "${MANAGEMENT_NODE_GROUP_NAME}"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "${MANAGEMENT_NODE_GROUP_ROLE}"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - metrics-server
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: metrics-server
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: metrics-server
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: metrics-server
